baseURL = "https://reef-pi.github.io/"
languageCode = "en-us"
title = "reef-pi - An opensource reef tank controller based on Raspberry Pi"
theme = "hugo-sustain"
googleAnalytics = "UA-102968086-1"

[params]
Author = "Ranjib Dey"
Description = "reef-pi - An opensource reef tank controller based on Raspberry Pi"
custom_css = ["css/img.css"]

[params.social]
  Github    = "reef-pi"
  Email     = "info@reef-pi.com"
  Twitter   = "reef_pi"

[[menu.main]]
  name = "guides"
  identifier = "guides"
  weight = 50
  url = "/guides/"

[[menu.main]]
  name = "additional documentation"
  identifier = "additional documentation"
  weight = 100
  url = "/additional-documentation/"
